### ISSUE TITLE
system prompt was not sent when conversestream invoke model 

### ISSUE THREAD

**Issue by turmind** [aws-samples/sample-client-for-amazon-bedrock#21]
I set system prompt in the chat setting, but, system prompt was not sent when conversestream invoke model

<img width="445" alt="image" src="https://github.com/user-attachments/assets/10502e24-dd9d-4ca4-bb3b-40c1b3e46c60">

reference: https://community.aws/content/2fgHnwf8V5ljrvxcbMcMF8Y5WLZ/amazon-bedrock-converse-api-system-prompts-and-inference-parameters?trk=2483aad2-15a6-4b7a-a1c5-189851586b67&sc_channel=el#step-7-send-the-request

**Comment by DamonDeng** [comment]
resolved in 7a0a1dd
